import type { ParsedABI, ParsedFunction, ParsedParam } from "./abi-parser.js";
import type { ABIEntry, ABIParam } from "../types/index.js";

/**
 * Generated TypeScript types for an ABI.
 */
export interface GeneratedTypes {
  name: string;
  types: string;
  registry: string;
  exports: string[];
}

/**
 * Generates TypeScript types from a parsed ABI.
 * Creates type-safe paramPath strings and function selectors.
 */
export function generateTypes(parsed: ParsedABI, moduleName: string): GeneratedTypes {
  const exports: string[] = [];
  const types: string[] = [];
  const registryEntries: string[] = [];

  const typeName = toPascalCase(moduleName);
  const abiConstName = `${toSnakeCase(moduleName)}_ABI`;

  types.push(`/**`);
  types.push(` * Auto-generated types for ${parsed.name}`);
  types.push(` * @generated by @clanker/gate-client`);
  types.push(` */`);
  types.push(``);

  types.push(`export const ${abiConstName} = ${JSON.stringify(toABIEntries(parsed), null, 2)} as const;`);
  exports.push(abiConstName);

  if (parsed.functions.length > 0) {
    const functionUnion = parsed.functions.map((f) => `"${f.name}"`).join(" | ");
    types.push(``);
    types.push(`/** Available function names */`);
    types.push(`export type ${typeName}FunctionName = ${functionUnion};`);
    exports.push(`${typeName}FunctionName`);

    for (const func of parsed.functions) {
      const funcTypeName = `${typeName}_${toPascalCase(func.name)}`;
      types.push(``);
      types.push(`/** Parameter paths for ${func.name}() */`);
      types.push(generateParamPaths(func, funcTypeName));
      exports.push(funcTypeName);

      types.push(``);
      types.push(`/** Selector for ${func.name}() */`);
      types.push(`export const ${funcTypeName}_SELECTOR = "${func.selector}" as const;`);
      exports.push(`${funcTypeName}_SELECTOR`);
    }

    types.push(``);
    types.push(`/** Function selectors */`);
    types.push(`export const ${typeName}_SELECTORS = {`);
    for (const func of parsed.functions) {
      types.push(`  ${func.name}: "${func.selector}",`);
    }
    types.push(`} as const;`);
    exports.push(`${typeName}_SELECTORS`);
  }

  registryEntries.push(`  ${typeName}: {`);
  registryEntries.push(`    abi: ${abiConstName},`);
  registryEntries.push(`    functions: {`);
  for (const func of parsed.functions) {
    const offsetMap = func.inputs
      .map((p) => `      "${p.name}": ${p.offset}`)
      .join(",\n");
    registryEntries.push(`      ${func.name}: {`);
    registryEntries.push(`        selector: "${func.selector}",`);
    registryEntries.push(`        offsets: {`);
    registryEntries.push(offsetMap);
    registryEntries.push(`        },`);
    registryEntries.push(`      },`);
  }
  registryEntries.push(`    },`);
  registryEntries.push(`  },`);

  return {
    name: moduleName,
    types: types.join("\n"),
    registry: registryEntries.join("\n"),
    exports,
  };
}

/**
 * Generates type-safe paramPath union for a function.
 */
function generateParamPaths(func: ParsedFunction, typeName: string): string {
  const paths = extractParamPaths(func.inputs, "");

  if (paths.length === 0) {
    return `export type ${typeName}ParamPath = never;`;
  }

  const pathUnion = paths.map((p) => `"${p}"`).join(" | ");
  return `export type ${typeName}ParamPath = ${pathUnion};`;
}

/**
 * Recursively extracts all parameter paths from inputs.
 */
function extractParamPaths(params: ParsedParam[], prefix: string): string[] {
  const paths: string[] = [];

  for (const param of params) {
    if (prefix) {
      paths.push(`${prefix}.${param.name.split(".").pop()}`);
    } else if (param.name) {
      paths.push(param.name);
    }
  }

  return paths;
}

/**
 * Converts ParsedABI back to ABIEntry[] for the registry.
 */
function toABIEntries(parsed: ParsedABI): ABIEntry[] {
  const entries: ABIEntry[] = [];

  for (const func of parsed.functions) {
    entries.push({
      name: func.name,
      type: "function",
      inputs: parsedParamsToABIParams(func.inputs),
      outputs: parsedParamsToABIParams(func.outputs),
      stateMutability: func.stateMutability,
    });
  }

  return entries;
}

/**
 * Converts ParsedParam[] to ABIParam[].
 */
function parsedParamsToABIParams(params: ParsedParam[]): ABIParam[] {
  return params.map((p) => ({
    name: p.name.includes(".") ? p.name.split(".").pop()! : p.name,
    type: p.type,
    components: p.components ? parsedParamsToABIParams(p.components) : undefined,
  }));
}

/**
 * Generates a complete module file.
 */
export function generateModuleFile(parsed: ParsedABI, moduleName: string): string {
  const generated = generateTypes(parsed, moduleName);

  const lines: string[] = [];
  lines.push(`/**`);
  lines.push(` * @clanker/gate-client - Auto-generated types for ${parsed.name}`);
  lines.push(` * `);
  lines.push(` * DO NOT EDIT - This file was generated from ABI.`);
  lines.push(` * Run \`pnpm run generate-types\` to regenerate.`);
  lines.push(` */`);
  lines.push(``);
  lines.push(generated.types);
  lines.push(``);

  return lines.join("\n");
}

/**
 * Generates an index file exporting all generated modules.
 */
export function generateIndexFile(modules: string[]): string {
  const lines: string[] = [];
  lines.push(`/**`);
  lines.push(` * @clanker/gate-client - Generated ABI types`);
  lines.push(` */`);
  lines.push(``);

  for (const mod of modules) {
    lines.push(`export * from "./${mod}.js";`);
  }

  return lines.join("\n");
}

/**
 * Generates the combined ABI registry.
 */
export function generateRegistryFile(entries: { name: string; abi: ABIEntry[] }[]): string {
  const lines: string[] = [];
  lines.push(`/**`);
  lines.push(` * @clanker/gate-client - Combined ABI Registry`);
  lines.push(` */`);
  lines.push(``);
  lines.push(`import type { ABIEntry } from "../types/index.js";`);
  lines.push(``);

  for (const entry of entries) {
    const constName = `${toSnakeCase(entry.name)}_ABI`;
    lines.push(`export const ${constName}: readonly ABIEntry[] = ${JSON.stringify(entry.abi, null, 2)} as const;`);
    lines.push(``);
  }

  lines.push(`export const GENERATED_REGISTRY = {`);
  for (const entry of entries) {
    lines.push(`  ${entry.name}: ${toSnakeCase(entry.name)}_ABI,`);
  }
  lines.push(`} as const;`);

  return lines.join("\n");
}

function toPascalCase(str: string): string {
  return str
    .replace(/[-_.](\w)/g, (_, c) => c.toUpperCase())
    .replace(/^(\w)/, (_, c) => c.toUpperCase());
}

function toSnakeCase(str: string): string {
  return str
    .replace(/([A-Z])/g, "_$1")
    .replace(/^_/, "")
    .toUpperCase();
}
